**Навка Гліб, ІПС-41**

**Варіант 12**


# Завдання 1


2, 3, 5, 14, 17, 18, 19, 20, 21

## 2

Вводиться число n. Розставити 1 та 0 у шаховому порядку, починаючи з 1 в матриці розміром n×n, використовуючи слайсінг

In [1]:
import numpy as np


def task2_iterative(n: int):
    zero_start_row = [i % 2 for i in range(n)]
    one_start_row = [(i + 1) % 2 for i in range(n)]

    result = [[] for _ in range(n)]

    result[0:n:2] = [zero_start_row for _ in range(n // 2 + n % 2)]
    result[1:n:2] = [one_start_row for _ in range(n // 2)]
    
    return result


def task2_numpy(n: int):
    result = np.zeros((n, n), dtype=int)

    result[1::2, ::2] = 1
    result[::2, 1::2] = 1

    return result


%timeit -n 100 -r 10 task2_iterative(100)
%timeit -n 100 -r 10 task2_numpy(100)

18.3 µs ± 1.58 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
6.33 µs ± 296 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 3

Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [2]:
def task3_iterative(n, m, r, c):
    return [[1 if i % r and j % c else 0 for j in range(0, m)] for i in range(0, n)]


def task3_numpy(n, m, r, c):
    res = np.ones((n, m), dtype=int)
    res[::r] = 0
    res[::c] = 0
    
    return res


%timeit -n 100 -r 10 task3_iterative(200, 300, 4, 5)
%timeit -n 100 -r 10 task3_numpy(200, 300, 4, 5)

5.4 ms ± 429 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
30.5 µs ± 8.32 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 5

Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [114]:
def task5_iterative(n: int):
    return [[[(i + 1) % 2] * n] for i in range(n)]


def task5_numpy(n: int):
    result = np.zeros((n, n), dtype=int)
    result[::2] = np.ones(n, dtype=int)


%timeit -n 100 -r 10 task5_iterative(200)
%timeit -n 100 -r 10 task5_numpy(200)

129 µs ± 2.11 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
6.94 µs ± 891 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 14

Розмістити на полі 8×8 нулі та одиниці в шахматному порядку, використовуючи функцію numpy tile().

In [113]:
def task14_iterative():
    n = 8
    return [[0, 1] * (n // 2) if i % 2 == 0 else [1, 0] * (n // 2) for i in range(n)]


def task14_numpy():
    n = 8
    template = np.array([[0, 1], [1, 0]])
    
    return np.tile(template, (n // 2, n // 2))


%timeit -n 100 -r 10 task14_iterative()
%timeit -n 100 -r 10 task14_numpy()


1.54 µs ± 33.4 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
5.53 µs ± 379 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 17

Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [110]:
def task17_iterative(n: int):
    result = [i for i in range(n + 1)]
    
    for i in range(len(result)):
        if i < n / 2 or i > 3 * n / 4:
            result[i] *= -1

    return result
        

def task17_numpy(n: int):
    result = np.arange(n + 1)
    result[(result < n / 2) | (result > 3 * n / 4)] *= -1

    return result


%timeit -n 100 -r 10 task17_iterative(100)
%timeit -n 100 -r 10 task17_numpy(100)

15.6 µs ± 258 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
7.36 µs ± 1.48 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 18

Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [108]:
import random


def task18_iterative(n: int):
    return len(set([random.randrange(0, 100) for _ in range(n)]))  


def task18_numpy(n: int):
    return len(np.unique(np.random.randint(0, 100, n)))


%timeit -n 100 -r 10 task18_iterative(200)
%timeit -n 100 -r 10 task18_numpy(200)

73.8 µs ± 3.73 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
19.3 µs ± 766 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 19

Згенерувати вектор із n елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести до 3 знаків після коми.

In [107]:
def task19_iterative(n: int):
    return [round(i / (n + 1), 3) for i in range(1, n + 1)]


def task19_numpy(n: int):
    return np.around(np.arange(1, n + 1) / (n + 1), 3)


%timeit -n 100 -r 10 task19_iterative(200)
%timeit -n 100 -r 10 task19_numpy(200)

83.9 µs ± 5.52 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
7.37 µs ± 1.21 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 20

Згенерувати вектор із n випадкових елементів, що лежать в інтервалі (0,1). Замінити максимальний елемент на 0.

In [109]:
def task20_iterative(n: int):
    result = [random.random() for _ in range(n)]
    result[result.index(max(result))] = 0

    return result


def task20_numpy(n: int):
    result = np.random.rand(n)
    result[result.argmax()] = 0

    return result


%timeit -n 100 -r 10 task20_iterative(200)
%timeit -n 100 -r 10 task20_numpy(200)

14.6 µs ± 2.41 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
2.86 µs ± 112 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 21

Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [102]:
import numpy as np


def task21_iterative(n: int, m: int):
    result = [[random.randint(0, m) for j in range(n)] for i in range(n)]
    max_element = max(max(result[i]) for i in range(n))

    for i in range(n):
        for j in range(n):
            if result[i][j] == max_element:
                result[i][j] *= -1

    return result


def task21_numpy(n: int, m: int):
    result = np.random.randint(0, m + 1, size=(n, n))
    max_element = np.max(result)
    
    result[result == max_element] *= -1

    return result
        

%timeit -n 100 -r 10 task21_iterative(100, 10)
%timeit -n 100 -r 10 task21_numpy(100, 10)

4.51 ms ± 16.7 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
141 µs ± 2.82 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


___

# Завдання 2


Розв'язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
* матричного множення
* оберненої матриці
* функції `numpy.linalg.solve()`

Порівняти всі рішення за допомогою функції `numpy.allclose()`.

$$
\begin{cases}
x_1 + x_2 - x_3 - x_4 = 0 \\
x_1 + 2x_3 - x_4 = 2 \\
x_1 - x_2 - x_4 = -1 \\
-x_1 + 3x_2 - 2x_3 = 1
\end{cases}
$$

In [97]:
coefficients = np.array([
    [1, 1, -1, -1],
    [1, 0, 2, -1],
    [1, -1, 0, -1],
    [-1, 3, -2, 0]
])

constant_terms = np.array([0, 2, -1, 0])

print(f"Матриця коефіцієнтів\n {coefficients}\n")
print(f"Вектор вільних членів\n {constant_terms}")

Матриця коефіцієнтів
 [[ 1  1 -1 -1]
 [ 1  0  2 -1]
 [ 1 -1  0 -1]
 [-1  3 -2  0]]

Вектор вільних членів
 [ 0  2 -1  0]


### Метод Крамера

In [98]:
import numpy as np


def cramer_method(coefficients, constant_terms):
    determinant = np.linalg.det(coefficients)
    size = coefficients.shape[0]
    
    if np.allclose(determinant, 0):
        raise "Determinant is zero, aborting"
    
    result = np.zeros(size)
    
    for i in range(size):
        temp_coefficients = np.copy(coefficients)
        temp_coefficients[:, i] = np.copy(constant_terms)
        
        result[i] = np.linalg.det(temp_coefficients) / determinant   
    
    return result

cramer_solution = cramer_method(coefficients, constant_terms)

print(f"Розв'язок методом Крамера\n {cramer_solution}")

Розв'язок методом Крамера
 [1. 1. 1. 1.]


### Матричне множення

In [99]:
matrix_mul_test = np.dot(coefficients, cramer_solution)

assert np.allclose(constant_terms, matrix_mul_test)

print(f"a * cramer_solution\n {matrix_mul_test}")


a * cramer_solution
 [ 6.66133815e-16  2.00000000e+00 -1.00000000e+00  4.44089210e-16]


### Обернена матриця

In [100]:
inverse_matrix_check = np.dot(np.linalg.inv(coefficients), constant_terms)

assert np.allclose(cramer_solution, inverse_matrix_check)

print(f"a ^ -1 * b\n {inverse_matrix_check}")

a ^ -1 * b
 [1. 1. 1. 1.]


### Розв'язок з використанням `numpy.linalg.solve()`

In [101]:
numpy_test = np.linalg.solve(coefficients, constant_terms)

assert np.allclose(numpy_test, cramer_solution)

print(numpy_test)

[1. 1. 1. 1.]


___

# Завдання 3


Обчислити значення матричного виразу
* з використанням універсальних функцій бібліотеки NumPy
* за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
* для обох випадків підрахувати час виконання скрипту та зробити висновок

Порівняти всі рішення за допомогою функції `numpy.allclose()`

$$
A(A^2 - B) - 2(B + A)B
$$

$$
A =
\begin{pmatrix}
2 & 3 & 1 \\
-1 & 2 & 4 \\
5 & 3 & 0
\end{pmatrix},

B = 
\begin{pmatrix}
2 & 7 & 13 \\
-1 & 0 & 5 \\
5 & 13 & 21
\end{pmatrix}
$$

In [78]:
a = [
    [2, 3, 1],
    [-1, 2, 4],
    [5, 3, 0]
]

b = [
    [2, 7, 13],
    [-1, 0, 5],
    [5, 13, 21]
]

np_a = np.array(a)
np_b = np.array(b)


### NumPy

In [86]:
def numpy_method():
    arg1 = np_a @ np.subtract(np_a @ np_a, np_b)
    arg2 = 2 * (np.add(np_b, np_a) @ np_a)

    return np.subtract(arg1, arg2)

### Ітеративні конструкції

In [87]:
def matrix_mul(a, b):
    a_columns = len(a[0])
    b_rows = len(b)

    assert a_columns == b_rows

    return [[sum([x * y for (x, y) in zip(a_row, b_col)]) for b_col in zip(*b)] for a_row in a]
    

def matrix_add(a, b):
    a_rows, a_columns = len(a), len(a[0])
    b_rows, b_columns = len(b), len(b[0])

    assert a_rows == b_rows and a_columns == b_columns

    return [[a[i][j] + b[i][j] for j in range(a_columns)] for i in range(a_rows)]


def matrix_sub(a, b):
    a_rows, a_columns = len(a), len(a[0])
    b_rows, b_columns = len(b), len(b[0])

    assert a_rows == b_rows and a_columns == b_columns

    return [[a[i][j] - b[i][j] for j in range(a_columns)] for i in range(a_rows)]


def scalar_matrix_mul(scalar, matrix):
    rows, cols = len(matrix), len(matrix[0])
    
    return [[matrix[i][j] * scalar for j in range(cols)] for i in range(rows)]


def iterative_method():
    arg1 = matrix_mul(a, matrix_sub(matrix_mul(a, a), b))
    arg2 = scalar_matrix_mul(2, matrix_mul(matrix_add(b, a), a))

    return matrix_sub(arg1, arg2)

### Висновок

In [118]:
print("Час виконання:")
%timeit -n 100 -r 10 numpy_method()
%timeit -n 100 -r 10 iterative_method()
print()

numpy_result = numpy_method()
iterative_result = iterative_method()

print(f"NumPy метод\n {numpy_result}\n")
print(f"Ітеративний метод\n {iterative_result}\n")
print(f"Рівні? ", np.allclose(numpy_result, iterative_result))

Час виконання:
6.72 µs ± 204 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
25.1 µs ± 657 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)

NumPy метод
 [[ -75  -85  -84]
 [ -40    0  -25]
 [-147 -171 -137]]

Ітеративний метод
 [[-75, -85, -84], [-40, 0, -25], [-147, -171, -137]]

Рівні?  True
